###
GET http://localhost:3001/api/persons

### code 200
GET http://localhost:3001/api/persons/6758614abadecd595fbdac25

### code 500 malformatted id
GET http://localhost:3001/api/persons/6758614abadec


### should be 204 if correct id
DELETE http://localhost:3001/api/persons/2

### should be 500 
DELETE http://localhost:3001/api/persons/222

### should be 200 and return created entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "George Boolean",
    "number": "021-323-123"
}

### should be 400 and return created entry
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "George Boolean",
    "number": "021-323-123"
}