###
GET http://localhost:3000/api/persons

### should be 204
DELETE http://localhost:3000/api/persons/2

### should be 404
DELETE http://localhost:3000/api/persons/222

### should be 200 and return created entry
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "George Boolean",
    "number": "021-323-123"
}

### should be 400 and return created entry
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "George Boolean",
    "number": "021-323-123"
}