###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Patek Philippe",
    "title": "Patek's mission",
    "url": "http://www.blog.patek.com",
    "likes": 99
}

@name = `$random.alphabetic(7)`

###
GET http://localhost:3003/api/users



###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "viktor smith",
    "username": "fjpeI988I",
    "password": "{{$guid}}"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Newblog post",
    "author": "Newauthor",
    "url": "newblog.com",
    "user": "67b713a91542c3ee99b83b98",
    "likes": "123231"
}
